### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by atomoc** [NicolasSiver/nodebb-plugin-ns-slugify#1]
Thanks for your support in this. But need, besides create, more "update" ;). And I use [transliteration](https://github.com/andyhu/node-transliteration), please try:

```
var translit = require('transliteration').slugify;

console.log(translit('проверка транслита', {separator: '_'}));
```

out: `proverka_translita`

**Comment by atomoc** [comment]
```
// { "hook": "filter:category.update", "method": "categoryUpdate" }
mod.categoryUpdate = function(params, callback) {

    if ( params.category.name )
    params.category.slug = params.cid + '/' + translit(params.category.name, {separator: '_'});


    callback(null, params);

};

// { "hook": "filter:topic.edit", "method": "topicEdit" }
mod.topicEdit = function(data, callback) {

    data.slug = data.slug.split('/')[0] + '/' + translit(data.slug.split('/')[1], {separator: '_'});


    callback(null, data);

};
```

**Comment by atomoc** [comment]
It should look something like this, and maybe that way :)

**Comment by NicolasSiver** [comment]
Will be added in next minor update.

**Comment by atomoc** [comment]
Thanks! :)

**Comment by atomoc** [comment]
Вот что я выдумал для использования модуля о котором говорил ранее:

```
mod.categoryUpdate = function(categoryData, callback) {

    if ( 'slug' in categoryData.category )
    categoryData.category.slug = categoryData.category.slug.split('/')[0] + '/' + translit(categoryData.category.name, {separator: '_'});


    callback(null, categoryData);

};
```

Он же подходит не только для русских символов, но и для китайских и других, которые прямо таки нуждаются в транслитерации. Настаиваю на использовании его ;)
Такая сложная выдумка потому что данный модуль заменяет "/" символ, в то время как slug выглядит так: 123/название. И на выходе получается: 123_nazvanie
